configfile: "configs/pipeline.yaml"

include: "workflow/rules/common.smk"
include: "workflow/rules/data_curator.smk"
include: "workflow/rules/marker_annotator.smk"
include: "workflow/rules/embedding_generator.smk"
include: "workflow/rules/domain_adapter.smk"
include: "workflow/rules/flux_predictor.smk"

rule all:
    input:
        ALL_TARGETS
