configfile: "configs/pipeline.yaml"

include: "rules/common.smk"
include: "rules/data_curator.smk"
include: "rules/marker_annotator.smk"
include: "rules/embedding_generator.smk"
include: "rules/feature_fusion.smk"
include: "rules/domain_adapter.smk"
include: "rules/flux_predictor.smk"

rule all:
    input:
        ALL_TARGETS
