#!/usr/bin/env python3
"""Generate pilot manifest and pipeline config for MUCC + rumen POC."""

from __future__ import annotations

import argparse
from pathlib import Path

SITES = ["OWC", "PPR", "JLA", "LA2", "STORDALEN", "SPRUCE"]
SITE_LABELS = {
    "OWC": "MUCC site OWC (Old Woman Creek)",
    "PPR": "MUCC site PPR (Prairie Pothole Region)",
    "JLA": "MUCC site JLA",
    "LA2": "MUCC site LA2",
    "STORDALEN": "MUCC site Stordalen Mire",
    "SPRUCE": "MUCC site SPRUCE",
}


def build_manifest(
    out_path: Path,
    rumen_count: int,
    mucc_per_site: int,
) -> list[str]:
    header = (
        "sample_id\tdomain\tecosystem\tdata_source\taccession\t"
        "has_flux\tflux_value\tflux_unit\tlatitude\tlongitude\t"
        "depth_cm\tsalinity_ppt\ttemperature_c\tcollection_date\tnotes"
    )

    rows = [header]
    sample_ids: list[str] = []

    for i in range(1, rumen_count + 1):
        sample_id = f"RUMEN_MAG_{i:03d}"
        sample_ids.append(sample_id)
        rows.append(
            "\t".join(
                [
                    sample_id,
                    "rumen",
                    "rumen",
                    "ENA",
                    "TBD",
                    "FALSE",
                    "NA",
                    "NA",
                    "NA",
                    "NA",
                    "NA",
                    "NA",
                    "NA",
                    "NA",
                    "PRJEB81441; methanogen MAG; replace accession",
                ]
            )
        )

    for site in SITES:
        for i in range(1, mucc_per_site + 1):
            sample_id = f"MUCC_MAG_{site}_{i:03d}"
            sample_ids.append(sample_id)
            rows.append(
                "\t".join(
                    [
                        sample_id,
                        "coastal",
                        "wetland",
                        "Zenodo",
                        "TBD",
                        "FALSE",
                        "NA",
                        "NA",
                        "NA",
                        "NA",
                        "NA",
                        "NA",
                        "NA",
                        "NA",
                        f"MUCC v2.0.0; {SITE_LABELS[site]}; replace MAG ID",
                    ]
                )
            )

    out_path.write_text("\n".join(rows) + "\n")
    return sample_ids


def write_pipeline(out_path: Path, sample_ids: list[str]) -> None:
    def format_list(items: list[str]) -> str:
        return "\n".join([f"  - {item}" for item in items])

    body = f"""# MethaNet Pilot Pipeline Config (MUCC v2.0.0 + rumen subset)
# Generated by poc/mucc_rumen_poc/scripts/generate_pilot_assets.py

simulate: false

stages:
  data_curator: false
  marker_annotator: true
  embedding_generator: true
  domain_adapter: false
  flux_predictor: false

paths:
  assemblies: data/assemblies
  hmm_dir: data/hmm
  marker_db: db/marker_db.mmsdb
  orfs: features/orfs
  marker_hits: features/marker_hits
  marker_sequences: features/marker_sequences
  dna_sequences: features/dna_sequences
  functional_features: features/functional
  embeddings: features/embeddings
  reports: reports
  figures: figures
  source_features: features/rumen.parquet
  target_features: features/coastal.parquet
  flux_features: features/all_features.parquet

assembly_samples:
{format_list(sample_ids)}

marker_samples:
{format_list(sample_ids)}

embedding_samples:
{format_list(sample_ids)}

dna_embedding_samples:
{format_list(sample_ids)}

threads:
  hmmer: 4
  mmseqs: 8
  embedding: 1
  qc: 8
  training: 1

models:
  esm2: facebook/esm2_t33_650M_UR50D
  dnabert2: zhihan1996/DNABERT-2-117M
  genomeocean: /path/to/GenomeOcean-4B.pt

embedding:
  genome_backend: dnabert2
  genome_dim: 768
  batch_size: 4
  device: cuda
  esm2:
    truncation_length: 1022
  dnabert2:
    max_length: 512

functional:
  evalue_threshold: 1e-10
  normalization: per_1k_proteins
"""
    out_path.write_text(body)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-dir", default="poc/mucc_rumen_poc")
    parser.add_argument("--rumen-count", type=int, default=120)
    parser.add_argument("--mucc-per-site", type=int, default=40)
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    manifest_path = out_dir / "manifest.tsv"
    sample_ids = build_manifest(manifest_path, args.rumen_count, args.mucc_per_site)

    pipeline_path = out_dir / "pipeline.yaml"
    write_pipeline(pipeline_path, sample_ids)

    print(f"Wrote {manifest_path}")
    print(f"Wrote {pipeline_path}")


if __name__ == "__main__":
    main()
