"""Schema constants for MethaNet feature and model interfaces."""

FEATURE_SCHEMA_VERSION = "1.0"

FUNCTIONAL_MARKERS = ("mcrA", "pmoA", "dsrA", "nifH", "cbbL")
FUNCTIONAL_BASE_DIM = len(FUNCTIONAL_MARKERS)
FUNCTIONAL_RATIO_DIM = 1
DEFAULT_FUNCTIONAL_PATHWAYS = 71
FUNCTIONAL_VECTOR_DIM = (
    FUNCTIONAL_BASE_DIM + FUNCTIONAL_RATIO_DIM + DEFAULT_FUNCTIONAL_PATHWAYS
)

ESM2_DIM = 1280
DNABERT2_DIM = 768
GENOMEOCEAN_DIM = 3072

DEFAULT_GENOME_BACKEND = "dnabert2"
DEFAULT_GENOME_DIM = DNABERT2_DIM

TOTAL_FUSED_DIM = FUNCTIONAL_VECTOR_DIM + ESM2_DIM + DEFAULT_GENOME_DIM
TOTAL_FUSED_DIM_GENOMEOCEAN = FUNCTIONAL_VECTOR_DIM + ESM2_DIM + GENOMEOCEAN_DIM
