#!/usr/bin/env python3
"""Check whether registered MethaNet atlas lanes are ready to consolidate.

The status JSON generated by summarize_atlas_lane_registry.py is the operational
source of truth. This gate turns its consolidation policy into an executable
preflight that can be used before launching cohort warehouse builds.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--status-json", type=Path, required=True)
    parser.add_argument(
        "--lane-id",
        action="append",
        default=[],
        help="Lane ID to check. May be repeated. Defaults to all non-current lanes.",
    )
    parser.add_argument(
        "--include-current-warehouses",
        action="store_true",
        help="Also report lanes whose warehouses are already current.",
    )
    parser.add_argument(
        "--print-commands",
        action="store_true",
        help="Print consolidation commands for ready lanes.",
    )
    return parser.parse_args()


def read_status_rows(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        raise SystemExit(f"Status JSON missing: {path}")
    data = json.loads(path.read_text())
    if not isinstance(data, list):
        raise SystemExit(f"Status JSON must contain a list of lane rows: {path}")
    return [row for row in data if isinstance(row, dict)]


def as_int(value: Any) -> int:
    try:
        return int(float(value or 0))
    except (TypeError, ValueError):
        return 0


def is_true(value: Any) -> bool:
    return str(value or "").strip().lower() == "true"


def lane_blockers(row: dict[str, Any]) -> list[str]:
    blockers: list[str] = []
    include_rows = as_int(row.get("functional_include_rows"))
    complete = as_int(row.get("functional_complete"))
    failed = as_int(row.get("functional_failed"))
    pending = as_int(row.get("functional_not_started")) + as_int(row.get("functional_partial"))
    if include_rows <= 0:
        blockers.append("functional_include_rows is zero")
    if failed:
        blockers.append(f"{failed} functional rows are failed")
    if pending:
        blockers.append(f"{pending} functional rows are pending/partial")
    if complete < include_rows:
        blockers.append(f"functional_complete {complete} is smaller than functional_include_rows {include_rows}")
    if not is_true(row.get("consolidation_ready")):
        blockers.append("consolidation_ready is not true")
    return blockers


def selected_rows(rows: list[dict[str, Any]], lane_ids: list[str], include_current: bool) -> list[dict[str, Any]]:
    if lane_ids:
        wanted = set(lane_ids)
        return [row for row in rows if str(row.get("lane_id") or "") in wanted]
    if include_current:
        return rows
    return [row for row in rows if not is_true(row.get("warehouse_current"))]


def main() -> int:
    args = parse_args()
    rows = read_status_rows(args.status_json)
    check_rows = selected_rows(rows, args.lane_id, args.include_current_warehouses)
    if args.lane_id:
        found = {str(row.get("lane_id") or "") for row in check_rows}
        missing = sorted(set(args.lane_id) - found)
        if missing:
            for lane_id in missing:
                print(f"BLOCKED {lane_id}: lane not found in status JSON")
            return 1
    if not check_rows:
        print("No lanes selected for consolidation gate check.")
        return 0

    failures = 0
    for row in check_rows:
        lane_id = str(row.get("lane_id") or "<missing>")
        if is_true(row.get("warehouse_current")):
            print(f"CURRENT {lane_id}: warehouse already current for registered functional denominator")
            continue
        blockers = lane_blockers(row)
        if blockers:
            failures += 1
            print(f"BLOCKED {lane_id}: " + "; ".join(blockers))
            continue
        print(f"READY {lane_id}: consolidation gate passed")
        if args.print_commands and row.get("consolidation_command"):
            print(row["consolidation_command"])
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
